spring.application.name=pattern



# Cloud Strorage file secret key and path
#AWS Credentials
aws.s3.bucketName=pattern
aws.s3.secretKey=pattern

#GCP Credentials
gcp.storage.bucketName=pattern
gcp.storage.secretKey=pattern

#Azure Credentials
azure.storage.bucketName=pattern
azure.storage.connectionString=pattern
azure.storage.secretKey=pattern
